config = {
  host: "https://2tm4g8tw:oxmznloz4xuttp4e@ginkgo-2006745.us-east-1.bonsai.io",
  transport_options: {
    request: { timeout: 5 }
  },
}

if File.exists?("config/elasticsearch.yml")
  config.merge!(YAML.load_file("config/elasticsearch.yml").symbolize_keys)
end

Elasticsearch::Model.client = Elasticsearch::Client.new(config)